### ISSUE TITLE
create group google calendar

### ISSUE THREAD

**Issue by R-Alan-Gamage** [Maxridenhour/tag#8]
I will create a group google calendar using the group email developer.gifttag@gmail.com

**Comment by R-Alan-Gamage** [comment]
https://calendar.google.com/calendar/render?tab=mc#main_7

Calendar set up; can we all commit to times we can work on #hashtag like I have? 

Is this the sort of calendar we were hoping for?

**Comment by khmurakami** [comment]
The email is developer.gifttag@gmail.com
Password is SaveTheW0rld!
